name: Discord Notification on Commit

on:
  push:
    branches:
      - main  

jobs:
  discord-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit details
        id: commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Send Discord notification
        uses: discord/action@v2
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_URL }}
          data: '{"embeds":[{"title":"New Commit","description":"Commit Message: ${{ steps.commit.outputs.message }}","color":16777215}]}'
